You can write your programs in any programming language. However, you will have to implement the algorithms yourself instead of using high-level library functions, except for solving a system of linear equations. Please provide a description of the data structures you use, any code-level optimizations you perform, any challenges you face, and of course, the requested outputs.

### Linear Regression

part 1

In [4]:
import numpy as np

filename = 'C:\\Users\Peter\\Desktop\\Classes\\INF 552\\Homework 4\\linear-regression.txt'
X_data = []
Y_data = []
with open(filename, "r") as file:
    content = file.read().splitlines()
    for line in content:
        temp = [1]
        for val in line.split(",")[:2]:
            temp.append(val)
        X_data.append(temp)
        Y_data.append(line.split(",")[2])
    
    # Solve with matrix computations W_opt = (D*DT)^-1 * D*y
    # D == X_data;  y == Y_data    
    
    X_data = np.mat(np.array(X_data).astype(float))
    Y_data = np.mat(np.array(Y_data).astype(float))

    
    X_new = X_data.T* X_data
    X_new = X_new.I
    Y_new = Y_data*X_data
    Y_new = Y_new.T

    weights = np.dot(X_new,Y_new,out=None).T
    print(weights)


[[0.01523535 1.08546357 3.99068855]]


Part II: Apply Library for linear regression 

In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np
filename = 'C:\\Users\Peter\\Desktop\\Classes\\INF 552\\Homework 4\\linear-regression.txt'

X_data = []
Y_data = []
with open(filename, "r") as file:
    content = file.read().splitlines()
    for line in content:
        temp = [1]
        for val in line.split(",")[:2]:
            temp.append(val)
        X_data.append(temp)
        Y_data.append(line.split(",")[2])
    
    
    X_data = np.mat(np.array(X_data).astype(float))
    Y_data = np.mat(np.array(Y_data).astype(float)).T

    linear_regression = LinearRegression(fit_intercept=False).fit(X_data, Y_data)
    lr_coef = linear_regression.coef_
    print(lr_coef)

[[0.01523535 1.08546357 3.99068855]]


### Logistic Regression

Part I: Implement Logistic Regression and run it on the points in the data file "classification.txt" ignoring the 4th column. That is, consider only the first 3 columns and the 5th column in each row. The first 3 columns are the coordinates of a point; and the 5th column is its classification label +1 or -1. Use the sigmoid function Ɵ(s) = es/(1+es).  Run up to 7000 iterations. Report your results (weights and accuracy after the final iteration). 

In [2]:
import sys 
import numpy as np

def sigmoid(x):
    return -1/(1+np.exp(x))

def gradient_descent(sig,X_data,Y_data):
    gradient = np.multiply(sig, np.multiply(X_data,Y_data))
    return np.sum(gradient, axis = 0)

def get_weights(weights, gradient, learning_rate):
    eta = learning_rate
    W = weights - eta * gradient
    return W

def error(countcorrect,len_vals):
    error = round(1 - int(countcorrect) / len_vals,4)
    return error

filename = 'C:\\Users\Peter\\Desktop\\Classes\\INF 552\\Homework 4\\classification.txt'
X_data = []
Y_data = []
eta = -.05 #learning late
count_correct = 0
count_incorrect = 0
with open(filename, "r") as file:
    content = file.read().splitlines()
    for line in content: #Split the data into attributes and classifiers 
        temp = [1]
        for val in line.split(",")[:3]:
            temp.append(val)
        X_data.append(temp)
        Y_data.append(line.split(",")[4])
        
    weights = [] #Randomly assign weights to each of the variables
    for i in range(len(X_data[0])):
        weights.append(np.random.uniform(0,1))
    weights = np.mat(np.array(weights))

    X_data = np.mat(np.array(X_data).astype(float))
    Y_data = np.mat(np.array(Y_data).astype(float)).T
    ywx = np.multiply((X_data * weights.T), Y_data)
    
    for i in range(7000): #iterate recursively 7000 times
        ywx = np.multiply((X_data * weights.T), Y_data)
        gradient = gradient_descent(sigmoid(ywx),X_data,Y_data) * -1/len(Y_data) #*-1/N
        weights = get_weights(weights,gradient,eta)
    
    print(weights)
    
    prediction = np.dot(X_data, weights.T)
    for i in range(len(prediction)):
        if prediction[i]>0:
            my_predict = 1
        else:
            my_predict = -1
            
        if Y_data[i] == my_predict:
            count_correct += 1
        else:
            count_incorrect += 1
    
    total_error = error(count_correct,len(Y_data))
    print(f'error of: {total_error}')

[[-0.03400825 -0.17574821  0.11572622  0.07828876]]
error of: 0.471


Part II

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
filename = 'C:\\Users\Peter\\Desktop\\Classes\\INF 552\\Homework 4\\classification.txt'
X_data = []
Y_data = []
eta = -.05 #learning late
count_correct = 0
count_incorrect = 0
with open(filename, "r") as file:
    content = file.read().splitlines()
    for line in content: #Split the data into attributes and classifiers 
        temp = [1]
        for val in line.split(",")[:3]:
            temp.append(val)
        X_data.append(temp)
        Y_data.append(line.split(",")[4])
    X_data = np.mat(np.array(X_data).astype(float))
    Y_data = np.mat(np.array(Y_data).astype(float)).T

    X_train, X_test, y_train, y_test = train_test_split(X_data, 
       Y_data, test_size=0.05, 
        random_state=101)
    
    logmodel = LogisticRegression(fit_intercept=False)
    logmodel.fit(X_train, y_train)
    
    predictions = logmodel.predict(X_test)
    coef = logmodel.coef_[0]
    print(coef)
    print(classification_report(y_test,predictions))

[-0.03287574 -0.16190844  0.10430366  0.08365111]
              precision    recall  f1-score   support

        -1.0       0.57      0.72      0.63        53
         1.0       0.55      0.38      0.45        47

    accuracy                           0.56       100
   macro avg       0.56      0.55      0.54       100
weighted avg       0.56      0.56      0.55       100



C:\Users\Peter\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Peter\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [159]:
X_train

matrix([[1.        , 0.37548293, 0.61170169, 0.06555911],
        [1.        , 0.51472457, 0.13894154, 0.55876299],
        [1.        , 0.59729199, 0.16808712, 0.90171251],
        ...,
        [1.        , 0.49932978, 0.00348945, 0.41113451],
        [1.        , 0.23532485, 0.65339908, 0.94110067],
        [1.        , 0.65529428, 0.86423406, 0.79394741]])